#Spring, JPA, Postgres, Mail configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tokinn
    username: postgres 
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: escomcrypto@gmail.com
    password: soporte123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

#OAuth configuration
facebook:
  client:
    clientId: 1624737334503803
    clientSecret: efd25dcde198d47ff5601000eec884f6
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
#Messenger Bot Configuration
messenger4j:
  appSecret: efd25dcde198d47ff5601000eec884f6
  verifyToken: aslkfjdasñdjfklj
  pageAccessToken: EAAXFsKOtKXsBAD1POeCLsOPNK1yJrmRCLZB4OZABgb7CEQ6lgm5tzey4xbKloAS4KgmRHAE4pYpvJ6d8CZAtChPzizUyHZC2ozJXhNmwMQqRZB5caShV25v4mUIZAs9ztVNfT4xXYC4uoXYZAQKp9MIBrZBL7Yit4SroZArmk3KZCIYkXTyF7j79y8
